### PR TITLE
Added skill based matchmaking

### PR DESCRIPTION
**Pull request by Mori01231**
SBMM will be disabled by default. Only enabled when SkillBasedMatchMaking: true in config.
SBMM takes into account the  sums of the "power level" of all the players on each team, and puts the player in the team that is deemed to be weaker.
The "power level" is determined by the K/D and total number of kills by a player.

### CODE REVIEW

**Comment by Mori01231** [comment]
Also fixed a bug where Rescue and gunfight doesn't end.
The code only handled cases where the next round would be started, and if that was the last round the stopGame function was called only after returning (so it didn't call the stopGame function at all).

**Comment by Mori01231** [comment]
Also fixed the laststand respawn bug.

**Review by mrrhetorical — CHANGES_REQUESTED** [review]
Please change on line 888 in GameInstance.java `if(sbmm == true)` to `if(sbmm)`.
Since you've modified what happens when a player kills themselves, please add another Lang enum value for when a player kills himself that says "You [killed] yourself" with the same formatting as in other kill messages to be sent when a player's killer is himself.

**Review by mrrhetorical — APPROVED** [review]
Looks good!

**Pull request merged**
